defmodule Dialectic.Ideas.IdeaGenerator do
  @moduledoc """
  A simple idea generator that creates interesting questions based on a given topic.
  """

  # List of question templates with a {topic} placeholder.
  @templates [
    "Let's talk about {topic}.",
    "What is the philosophy of {topic}?",
    "How does {topic} challenge our conventional thinking?",
    "What is the deeper meaning behind {topic}?",
    "Could you elaborate on the complexities of {topic}?",
    "How does {topic} connect to contemporary debates?",
    "What if we viewed {topic} from an unconventional perspective?",
    "What are the first principles behind {topic}?",
    "How has the idea of {topic} evolved over time?",
    "What are the strongest arguments for and against {topic}?",
    "What hidden assumptions are often made about {topic}?",
    "What are the most common misconceptions about {topic}?",
    "How would you explain {topic} to a curious 10-year-old?",
    "How would an expert critique the mainstream view of {topic}?",
    "What would a skeptic argue about {topic}?",
    "What are the ethical implications of {topic}?",
    "How does {topic} intersect with economics, psychology, and culture?",
    "What simple mental models help reason about {topic}?",
    "What are the main trade-offs involved in {topic}?",
    "What failure modes should we anticipate with {topic}?",
    "What would a red-team test of {topic} reveal?",
    "What would falsify the core claims about {topic}?",
    "What are the measurable indicators of progress in {topic}?",
    "What are the edge cases or extremes that stress-test {topic}?",
    "Where does {topic} break down in practice?",
    "What historical case studies illuminate {topic}?",
    "How might we design a small experiment to explore {topic}?",
    "What metaphors clarify or distort our understanding of {topic}?",
    "Which stakeholders win or lose under {topic}?",
    "How does {topic} reshape incentives and behavior?",
    "What are the long-term second- and third-order effects of {topic}?",
    "How does {topic} change across different cultural contexts?",
    "What are the key concepts and terms to define before debating {topic}?",
    "How would you teach {topic} in a 60-minute seminar?",
    "What is the 80/20 of understanding {topic}?",
    "What invariants remain true as {topic} scales up or down?",
    "What adjacent fields offer useful analogies for {topic}?",
    "How does {topic} interact with power, identity, and institutions?",
    "If {topic} succeeds wildly, what new problems emerge?",
    "If {topic} fails, what does the postmortem say?",
    "What does a systems diagram of {topic} look like?",
    "How could we measure the opportunity cost around {topic}?",
    "What open questions about {topic} are most tractable right now?"
  ]

  @topics [
    "Meta-rationality",
    "Blood Meridian",
    "Existentialism",
    "Quantum Mechanics",
    "Artificial Intelligence",
    "Cybernetics",
    "Postmodernism",
    "Phenomenology",
    "Absurdism",
    "Deep Ecology",
    "Chaos Theory",
    "Epistemology",
    "Cryptography",
    "Semiotics",
    "Futurism",
    "Dystopian Literature",
    "Solipsism",
    "Transhumanism",
    "Virtual Reality",
    "Social Constructivism",
    "Interdisciplinary Research",
    "Emergent Behavior",
    "Ontology",
    "Fractal Geometry",
    "Neural Networks",
    "Simulation Theory",
    "Game Theory",
    "Biopolitics",
    "Cyberpunk",
    "Existential Risk",
    "Posthumanism",
    "Speculative Realism",
    "New Materialism",
    "Anthropocene",
    "Cognitive Science",
    "Complex Systems",
    "Artificial Consciousness",
    "Economic Philosophy",
    "Digital Humanities",
    "Aesthetics in the Digital Age",
    "Structuralism",
    "Romanticism",
    "Gothic Literature",
    "Modernist Literature",
    "Literary Criticism",
    "Philosophy of Science",
    "Evolutionary Psychology",
    "Moral Philosophy",
    "Spirituality in Modern Life",
    "Philosophy of Technology",
    "Post-structuralism",
    "Neo-noir cinema",
    "Digital art and NFTs",
    "Existential dread in modern society",
    "Climate change policy",
    "Cyber security ethics",
    "Transcendental meditation",
    "The philosophy of mind",
    "Multiverse theory",
    "Cognitive biases in decision making",
    "Postcolonial theory",
    "Urban planning and architecture",
    "The future of education",
    "Virtual economies",
    "Consciousness and psychedelics",
    "Ethical implications of gene editing",
    "Technological singularity",
    "Spirituality and science",
    "Epigenetics and behavior",
    "Intersection of art and technology",
    "Feminist theory",
    "Minimalism in art and lifestyle",
    "AI and creativity",
    "History of philosophy",
    "Social media’s influence on society",
    "The evolution of language",
    "Environmental ethics",
    "The rise of cryptocurrency",
    "Digital surveillance",
    "The power of narrative",
    "Artificial life and robotics",
    "Existential psychotherapy",
    "Memory and identity",
    "Philosophy of literature",
    "The future of work",
    "Biotechnology advancements",
    "Space exploration and ethics",
    "Political philosophy in the digital age",
    "Emotional intelligence",
    "Globalization and cultural identity",
    "Post-truth politics",
    "Cognitive science and artificial intelligence",
    "Digital transformation in business",
    "The art of storytelling",
    "Historical narratives and myth-making",
    "Behavioral economics",
    "The impact of automation on society",
    "Virtual reality and human connection",
    "New media art",
    "Gnosticism",
    "Transcendentalism",
    "Existentialism",
    "Nihilism",
    "Liberation",
    "Liberalism",
    "Libertarianism",
    "Positive Freedom",
    "Negative Freedom",
    "Equality",
    "Justice",
    "Dadaism",
    "The evolution of music in the digital era",
    "Blood Meridian by Cormac McCarthy",
    "Zen and the Art of Motorcycle Maintenance by Robert M. Pirsig",
    "Gödel, Escher, Bach: An Eternal Golden Braid by Douglas Hofstadter",
    "The Structure of Scientific Revolutions by Thomas S. Kuhn",
    "The Demon-Haunted World by Carl Sagan",
    "A Brief History of Time by Stephen Hawking",
    "Cosmos by Carl Sagan",
    "The Selfish Gene by Richard Dawkins",
    "Bullshit Jobs: A Theory by David Graeber",
    "The Singularity Is Near by Ray Kurzweil",
    "Life 3.0: Being Human in the Age of Artificial Intelligence by Max Tegmark",
    "Superintelligence: Paths, Dangers, Strategies by Nick Bostrom",
    "The Information: A History, a Theory, a Flood by James Gleick",
    "Chaos: Making a New Science by James Gleick",
    "Complexity: A Guided Tour by Melanie Mitchell",
    "The Elegant Universe by Brian Greene",
    "The Fabric of the Cosmos by Brian Greene",
    "The Hidden Reality: Parallel Universes and the Deep Laws of the Cosmos by Brian Greene",
    "Man’s Search for Meaning by Viktor E. Frankl",
    "The Idiot by Fyodor Dostoevsky",
    "The Brothers Karamazov by Fyodor Dostoevsky",
    "Small is beautiful by E.F. Schumacher",
    "Crime and Punishment by Fyodor Dostoevsky",
    "Being and Nothingness by Jean-Paul Sartre",
    "Fear and Trembling by Søren Kierkegaard",
    "The Stranger by Albert Camus",
    "Nausea by Jean-Paul Sartre",
    "The Myth of Sisyphus by Albert Camus",
    "Meditations by Marcus Aurelius",
    "The Republic by Plato",
    "Beyond Good and Evil by Friedrich Nietzsche",
    "Thus Spoke Zarathustra by Friedrich Nietzsche",
    "The Birth of Tragedy by Friedrich Nietzsche",
    "The Prince by Niccolò Machiavelli",
    "The Social Contract by Jean-Jacques Rousseau",
    "The Communist Manifesto by Karl Marx and Friedrich Engels",
    "Capitalism and Freedom by Milton Friedman",
    "The Wealth of Nations by Adam Smith",
    "The Road to Serfdom by Friedrich Hayek",
    "The Age of Surveillance Capitalism by Shoshana Zuboff",
    "Algorithms to Live By by Brian Christian and Tom Griffiths",
    "The Master Algorithm by Pedro Domingos",
    "The Rise and Fall of the Third Reich by William L. Shirer",
    "A People’s History of the United States by Howard Zinn",
    "The End of History and the Last Man by Francis Fukuyama",
    "The Black Swan: The Impact of the Highly Improbable by Nassim Nicholas Taleb",
    "Antifragile: Things That Gain from Disorder by Nassim Nicholas Taleb",
    "Skin in the Game: Hidden Asymmetries in Daily Life by Nassim Nicholas Taleb",
    "Thinking, Fast and Slow by Daniel Kahneman",
    "Predictably Irrational by Dan Ariely",
    "The Art of War by Sun Tzu",
    "The Conquest of Happiness by Bertrand Russell",
    "The Master and His Emissary: The Divided Brain and the Making of the Western World by Iain McGilchrist",
    "Digital Minimalism: Choosing a Focused Life in a Noisy World by Cal Newport",
    "The Road to Serfdom by Friedrich Hayek",
    "Mere Christianity by C.S. Lewis"
  ]

  def run do
    generate_question(Enum.random(@topics))
  end

  def all do
    Enum.map(@topics, &generate_question/1)
  end

  @doc """
  Generates a single question based on the provided topic.
  """
  def generate_question(topic) when is_binary(topic) do
    template = Enum.random(@templates)
    String.replace(template, "{topic}", topic)
  end

  @doc """
  Generates a list of questions based on the provided topic and count.
  """
  def generate_questions(topic, count)
      when is_binary(topic) and is_integer(count) and count > 0 do
    1..count
    |> Enum.map(fn _ -> generate_question(topic) end)
  end
end
